export const inputItems = [
  { label: '你是一名', placeholder: 'SEO专业写手', single: true },
  { label: '背景情况', placeholder: '优化后的博客文章', single: true },
  { label: '你的任务', placeholder: '调研关键词并自然地融入内容中', single: false },
  { label: '在过程中你应当', placeholder: '注重可读性、相关性和关键词合理分布', single: false },
  { label: '请注意', placeholder: '避免关键词堆砌', single: false },
  { label: '输出格式', placeholder: '纯文本', single: true },
  { label: '示例', placeholder: '标题：高效SEO写作的10个技巧，助力内容提升可见度', single: false },
];

export const defaultRoleOptions = [
  { label: '资深会计师', value: '资深会计师' },
  { label: '高级软件开发工程师', value: '高级软件开发工程师' },
  { label: '资深教师', value: '资深教师' },
  { label: '优秀销售代表', value: '优秀销售代表' },
  { label: '胜任的项目经理', value: '胜任的项目经理' },
  { label: '专业律师', value: '专业律师' },
  { label: '合格工程师', value: '合格工程师' },
  { label: '资深建筑师', value: '资深建筑师' },
  { label: '胜任的市场经理', value: '胜任的市场经理' },
  { label: '知识渊博的财务分析师', value: '知识渊博的财务分析师' },
  { label: '有创意的平面设计师', value: '有创意的平面设计师' },
  { label: '资深人力资源经理', value: '资深人力资源经理' },
  { label: '值得信赖的顾问', value: '值得信赖的顾问' },
  { label: '技术娴熟的医生', value: '技术娴熟的医生' },
  { label: '持证心理学家', value: '持证心理学家' },
  { label: '敬业的研究员', value: '敬业的研究员' },
  { label: '分析型数据分析师', value: '分析型数据分析师' },
  { label: '敏锐的经济学家', value: '敏锐的经济学家' },
  { label: '新闻记者', value: '新闻记者' },
  { label: '专业药剂师', value: '专业药剂师' },
  { label: '有同理心的社工', value: '有同理心的社工' },
  { label: '技术型IT专家', value: '技术型IT专家' },
  { label: '有洞察力的商业分析师', value: '有洞察力的商业分析师' },
  { label: '资深运营经理', value: '资深运营经理' },
  { label: '战略活动策划师', value: '战略活动策划师' },
  { label: '资深房地产经纪人', value: '资深房地产经纪人' },
  { label: '资深投资银行家', value: '资深投资银行家' },
  { label: '专业Web开发工程师', value: '专业Web开发工程师' },
  { label: '认证健身教练', value: '认证健身教练' },
  { label: '专业高管教练', value: '专业高管教练' },
  { label: '敏捷Scrum Master', value: '敏捷Scrum Master' },
  { label: '网络安全分析师', value: '网络安全分析师' },
  { label: '用户体验（UX）研究员', value: '用户体验（UX）研究员' },
  { label: '区块链开发工程师', value: '区块链开发工程师' },
  { label: '人工智能工程师', value: '人工智能工程师' },
  { label: '环境顾问', value: '环境顾问' },
  { label: '数据隐私官', value: '数据隐私官' },
  { label: '虚拟现实（VR）开发工程师', value: '虚拟现实（VR）开发工程师' },
  { label: '道德黑客', value: '道德黑客' },
];

export const defaultTaskOptions = [
  { label: '适应', value: '适应' },
  { label: '分析', value: '分析' },
  { label: '自动化', value: '自动化' },
  { label: '计算', value: '计算' },
  { label: '分类', value: '分类' },
  { label: '协作', value: '协作' },
  { label: '转换', value: '转换' },
  { label: '定制', value: '定制' },
  { label: '调试', value: '调试' },
  { label: '设计', value: '设计' },
  { label: '检测', value: '检测' },
  { label: '诊断', value: '诊断' },
  { label: '发现', value: '发现' },
  { label: '增强', value: '增强' },
  { label: '促进', value: '促进' },
  { label: '筛选', value: '筛选' },
  { label: '生成', value: '生成' },
  { label: '识别', value: '识别' },
  { label: '改进', value: '改进' },
  { label: '优化', value: '优化' },
  { label: '个性化', value: '个性化' },
  { label: '预测', value: '预测' },
  { label: '排序', value: '排序' },
  { label: '识别', value: '识别' },
  { label: '推荐', value: '推荐' },
  { label: '模拟', value: '模拟' },
  { label: '精简', value: '精简' },
  { label: '总结', value: '总结' },
  { label: '跟踪', value: '跟踪' },
  { label: '翻译', value: '翻译' },
  { label: '验证', value: '验证' },
];

export const defaultOutputFormatOptions = [
  { label: '纯文本', value: 'plain text' },
  { label: '结构化格式', value: 'well structured format' },
  { label: 'JSON', value: 'JSON' },
  { label: 'CSV', value: 'CSV' },
  { label: 'HTML', value: 'HTML' },
  { label: 'XML', value: 'XML' },
  { label: 'Markdown代码', value: 'Markdown code' },
  { label: 'PDF', value: 'PDF' },
];

export const LS_ROLE_KEY = 'promptcraft_roles';
export const LS_TASK_KEY = 'promptcraft_tasks';
export const LS_FORMAT_KEY = 'promptcraft_formats'; 